# Generated by Django 4.1.4 on 2023-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('point', models.TextField(verbose_name='頑張ったところ')),
                ('dissapoint', models.TextField(verbose_name='直したいところ')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
